version: '3.8'
services:

  mosquitto:
    image: cro/mqtt:latest
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - internal
    environment:
      - MOSQUITTO_PASSWORDFILE=${MOSQUITTO_PASSWORDFILE}
    volumes:
      - mosquitto-conf:/home/mac/Infrastructure/mosquitto/config
      - mosquitto-data:/home/mac/Infrastructure/mosquitto/data
      - mosquitto-logs:/home/mac/Infrastructure/mosquitto/log

networks:
  internal:
    driver: overlay

volumes:
  mosquitto-conf:
  mosquitto-data:
  mosquitto-logs: