spring:
  application:
    name: measurement-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: crbk-project
      username: admin
      password:
      authentication-database: admin
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password:
    measurement-exchange: measurement
    measured-routing-key: measured
    measured-queue: measured.queue

management:
  endpoints:
    web:
      exposure:
        include: info, health, configprops
