spring:
  application:
    name: crbk-project
  data:
    mongodb:
      host: mac-primergy
      port: 27017
      database: crbk-project
      username:
      password:
      authentication-database: admin
  security:
    user:
      name:
      password:
      roles: ADMIN

integration:
  mqtt:
    url: tcp://mac-primergy:1883
    client-id: instance
    topics:
      - soil-moisture
      - temperature
