spring:
  application:
    name: crbk-project
  data:
    mongodb:
      host: mac-primergy
      port: 27017
      database: crbk-project
      username: admin
      password: password
      authentication-database: admin

  mqtt:
    url: tcp://mac-primergy:1883
    client-id: local-instance
    topics:
      - soil-moisture
      - temperature
