spring:
  application:
    name: measurement-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: measurements
      username: admin
      password: password
      authentication-database: admin
  security:
    user:
      name: admin
      password: "{noop}password"
      roles: ADMIN
  rabbitmq:
    host: localhost
    port: 5432
    username: admin
    password: password
