spring:
  application:
    name: iot-service

integration:
  mqtt:
    hostname: mac-primergy:1883
    url: tcp://${integration.mqtt.hostname}
    client-id: iot-app
    topics:
      - soil-moisture-sensor
      - temperature-sensor
  elasticsearch:
    endpoint: mac-primergy:9200

logging:
  level:
    org.springframework.data.convert.CustomConversions: ERROR

spring.influx