spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: measurements
      username: admin
      password: password
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 5432
    username: admin
    password: password
