spring:
  application:
    name: iot-service

integration:
  influx:
    url: http://mac-primergy:8086
    token: tn4fVNEKxn5RNzy-apO0LkXNon8nm1yCNqj97i3KA9j6GkmX-vvYISvqORHqwKdP5kyVnwFkNXxlVEpMOX89gA==

  mqtt:
    url: tcp://mac-primergy:1883
    client-id: iot-app
    topics:
      - soil-moisture-sensor
      - temperature-sensor

logging:
  level:
    org.springframework.data.convert.CustomConversions: ERROR
