spring:
  application:
    name: crbk-project
  data:
    mongodb:
      host: localhost
      port: 27017
      database: crbk-project
      username: admin
      password: password
      authentication-database: admin
  security:
    user:
      name: admin
      password: {noop}password
      roles: ADMIN

integration:
  mqtt:
    url: tcp://localhost:1883
    client-id: local-instance
    topics:
      - soil-moisture
      - temperature
