spring:
  application:
    name: crbk-project
  data:
    mongodb:
      host: mac-primergy
      port: 27017
      database: crbk-project
      username: admin
      password: IoT2021!
      authentication-database: admin
  security:
    user:
      name: admin
      password: "{noop}IoT2021!"
      roles: ADMIN

integration:
  mqtt:
    url: tcp://mac-primergy:1883
    client-id: local-instance
    topics:
      - soil-moisture
      - temperature
